# NumPy Library

stands for - Numerical python

Supports : multi-dimensional arrays, 
           mathematical functions, 
           linear algebra,
           random number generation, and more .

### Installation of NumPy

In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


### to check version of numpy

In [4]:
import numpy as np
print(np.__version__)


1.26.4


## NumPy Arrays

In [8]:
import numpy as np

# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])  # any iterable sequence of definite length
print(arr1)

# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### Basic Properties

1. Homogeneous elements : elements should be of same ddata type

2. Contiguous : elements are stored in contiguous memory blocks 

3. Fixed size : once created , it has a fixed size

4. Multidimensional : can be of multiple dimensions 1D, 2D, 3D

5. Vectorized Operations : allows element-wise operations

6. Mutable : can be modified

7. Efficient memory usage : consumes less memory than list

## creating array using built in functions :

In [30]:
# Array of zeros
zeros_array = np.zeros((3, 3))
print(zeros_array)




[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
# Array of ones
ones_array = np.ones((2, 2))
print(ones_array)


[[1. 1.]
 [1. 1.]]


In [38]:
# Identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Array with a range of numbers
range_array = np.arange(1, 10, 2)

# Array with evenly spaced values
linspace_array = np.linspace(1, 10, 5)

# Random array
random_array = np.random.rand(3, 3)  # Uniform distribution
random_int_array = np.random.randint(1, 10, (2, 3))  # Random integers