# NumPy Library

stands for - Numerical python

Supports : multi-dimensional arrays, 
           mathematical functions, 
           linear algebra,
           random number generation, and more .

### Installation of NumPy

In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


### to check version of numpy

In [8]:
import numpy as np
print(np.__version__)


1.26.4


## NumPy Arrays

In [10]:
import numpy as np

# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])  # any iterable sequence of definite length
print(arr1)

# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### Basic Properties

1. Homogeneous elements : elements should be of same ddata type

2. Contiguous : elements are stored in contiguous memory blocks 

3. Fixed size : once created , it has a fixed size

4. Multidimensional : can be of multiple dimensions 1D, 2D, 3D

5. Vectorized Operations : allows element-wise operations

6. Mutable : can be modified

7. Efficient memory usage : consumes less memory than list

## creating array using built in functions :

In [30]:
# Array of zeros
zeros_array = np.zeros((3, 3))
print(zeros_array)




[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
# Array of ones
ones_array = np.ones((2, 2))
print(ones_array)


[[1. 1.]
 [1. 1.]]


In [38]:
# Identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
# Array with a range of numbers
range_array = np.arange(1, 19, 2)
print(range_array)




[ 1  3  5  7  9 11 13 15 17]


In [38]:
# Array with evenly spaced values
linspace_array = np.linspace(1, 12, 5)
print(linspace_array)



[ 1.    3.75  6.5   9.25 12.  ]


In [52]:
# Random array
random_array = np.random.rand(3, 3)  # Uniform distribution
print(random_array)


[[0.61958112 0.49652393 0.635418  ]
 [0.04555392 0.13066839 0.81214354]
 [0.78942812 0.38038871 0.63671534]]


In [56]:
# random inntegers
random_int_array=np.random.randint(1, 10,(3,3))
print(random_int_array)

[[8 6 5]
 [9 9 4]
 [1 4 5]]


### Array Attributes

In [62]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)  # (rows, columns)

print(arr.ndim)   # Number of dimensions

print(arr.size)   # Total elements

print(arr.dtype)  # Data type

print(arr.itemsize)  # Size of one element in bytes


(2, 3)
2
6
int32
4


### Array Reshaping and Flattening

In [75]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape((3, 2)) # m*n should be = to no. of elements
print(reshaped_arr)


flattened_arr = reshaped_arr.flatten() # reverses the previous process
print(flattened_arr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


### Concatenation and Splitting

In [85]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenation
concatenated = np.concatenate((a, b))
print(concatenated)

# Splitting
split_arr = np.split(concatenated, 2)
print(split_arr)

[1 2 3 4 5 6]
[array([1, 2, 3]), array([4, 5, 6])]


### Indexing and Slicing

In [94]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print()

# Accessing elements
print(arr[0, 1])  # Element at row 0, column 1
print()

# Slicing (rows:columns)
print(arr[:, 1])  # All rows, second column
print()
print(arr[1:, :2])  # Rows 1 onwards, first two columns


[[1 2 3]
 [4 5 6]
 [7 8 9]]

2

[2 5 8]

[[4 5]
 [7 8]]


### Mathematical Operations

#### 1. Basic operations

In [100]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise operations
sum_arr = arr1 + arr2
diff_arr = arr1 - arr2
prod_arr = arr1 * arr2
div_arr = arr1 / arr2
print(sum_arr, diff_arr, prod_arr, div_arr)


[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ]


#### 2. Aggregate Functions

In [104]:
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))  # Sum of elements
print(np.mean(arr))  # Mean
print(np.median(arr))  # Median
print(np.std(arr))  # Standard deviation
print(np.min(arr))  # Minimum value
print(np.max(arr))  # Maximum value


15
3.0
3.0
1.4142135623730951
1
5


#### 3. Matrix Operations

In [115]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix multiplication
result = np.dot(matrix1, matrix2)
print(result)
print()

# Transpose
transposed = matrix1.T
print(transposed)
print()

# Inverse
inverse_matrix = np.linalg.inv(matrix1)
print(inverse_matrix)


[[19 22]
 [43 50]]

[[1 3]
 [2 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


### Random Module

In [128]:
# Generate random numbers
rand_num = np.random.rand(3)  # 3 random numbers between 0 and 1
print(rand_num)

rand_int = np.random.randint(1, 10, (2, 2))  # 2x2 random integers from 1 to 9
print(rand_int)

# Shuffle an array
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[0.52276504 0.15584666 0.31305991]
[[4 8]
 [2 4]]
[3 1 5 2 4]


### Copying and View in NumPy

In [ ]:
# Shallow copy (view)
arr = np.array([1, 2, 3])
view_arr = arr.view()
view_arr[0] = 99  # Modifies original array

# Deep copy
copy_arr = arr.copy()
copy_arr[0] = 100  # Does not modify original array
